steady_timer: steady_timer.cpp
	g++ $^ --std=c++11  -lboost_system -lboost_thread-mt -lpthread -o $@
coroutine: coroutine.cpp
	g++ $^ --std=c++2a -lboost_coroutine -lboost_system -lboost_thread-mt -lpthread -o $@
