eval `gdircolors ~/.dircolors.256dark`
alias -g ls='gls --color=auto'
alias -g  ll='gls -l --color=auto'
alias -g  dev='ssh test@10.12.77.132'
alias typora="open -a typora"
#autoload -Uz compinit && compinit
PROMPT='%2~ %# '

autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT=\$vcs_info_msg_0_
#zstyle ':vcs_info:git:*' formats '%F{100}(%b)%r%f'
zstyle ':vcs_info:git:*' formats '%F{100}(%b)%f'
zstyle ':vcs_info:*' enable git

export PATH=/usr/local/bin/:$HOME/go/bin:$HOME/bin:$PATH
export GO111MODULE=auto

# config autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
